# Generated by Django 5.2 on 2025-06-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VariantOption',
            new_name='SubVariant',
        ),
        migrations.RenameModel(
            old_name='ProductVariant',
            new_name='Variant',
        ),
    ]
