# Generated by Django 5.2 on 2025-06-25 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0002_rename_variantoption_subvariant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('-CreatedDate', 'ProductID'), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
